public class CPAsset {
    
    public CPAsset()
    {
        
    }
    public string SerialNumber{get;set;}
    public integer BaseNode{get;set;}
    public integer PlusNode{get;set;}
    public integer BoostNode{get;set;}
    public long ExpiryDate{get;set;}
    public long startDate{get;set;}
    public long endDate{get;set;}
    public string salesforceId {get;set;}
    public string id{get;set;}
    public string name{get;set;}
    public decimal quantity{get;set;}
    
}