public class ECAssetViewController {
    
    
    
    
    
    
    
    public class ECAssetViewWrapper
    {
        public string AccountName{get;set;}
        public string ProductName{get;set;}
        public string Status{get;set;}
        public integer Quantity{get;set;}
        public Date ShipDate {get;set;}
        public Date POCContractEndDate{get;set;}
        public Date MaintContractEndDate{get;set;}
        public Date SmartHandsContractEndDate{get;set;}
        public string ContractNotes{get;set;}
    }
 }