public class POCLegacyDataConversion {
    
    
    // Step 1
    public static void ConvertToEvalQuotes()
    {
        
        
     // Take all the POC where Convert=true
     // Loop over the POCs and create an eval opp and eval quote 
     // Loop over the physical products and virtual products 
     // for physical, call method from Custom POC Request and add in quote lineaddresss 2) add subscriptiopn line items
     // for virtual, add subscription line items into quote line
     // 
     
        
        
        
        
    }
    
     // Step 2
    public static void ConvertNXVXShippedAssets()
    {
        
        
        
        
        
    }
     // Step 3
    public static void ConvertECShippedAssets()
    {
        
        
        
        
        
    }
     // Step 4
    public static void ConvertServiceProviderAssets()
    {
        
        
        
        
        
    }
     // Step 5
    public static void AssociateRMARecordTOEvalQuotes()
    {
        
        
        
        
        
    }
    
    
    

}