@IsTest
public class TestClearRequestEndDate {
    
    
    @IsTest
    public static void ClearRequestEndDate_Test()
    {
        Account acc = new Account(Name='Test Acc');
        insert acc;
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'acme';
        opportunity.AccountId = acc.Id;
        opportunity.Pricebook2Id = TestUtilities.getStandardPricebookId();
        opportunity.StageName = 'Closed Dead';
        opportunity.Dead_Reason__c = 'acme';
        opportunity.CloseDate = Date.today().addYears(1);
        opportunity.Type = 'New Business';
        opportunity.Opportunity_Source__c = 'Other';
        opportunity.POC_Type__c = 'POC';
        opportunity.Product_Type__c = 'Both';
        opportunity.Deal_Type__c = 'Replication';
        opportunity.Solution_Type__c = 'Replication Acceleration';
        
        insert opportunity;
        
        Contact contact = new Contact(FirstName = 'AcmeFirstname', LastName = 'AcmeLastname', Phone='123456789', Email = 'acme@acme.com' );
        insert contact;
        Request__c request = new Request__c(POC_Contact__c = contact.Id);
        request.POC_Type__c='EdgeConnect';
        request.Extension_Justification__c='Test';
        request.TR_Approved__c=true;
        request.RSM_Approved__c=true;
        request.Type__c='Evaluation';
        request.Submission_Condition_Satisfied__c=true;
        request.Target_End_Date__c=Date.today().adddays(5);
        request.Status__c='Shipped';
        request.Opportunity__c=opportunity.Id;
        request.RSM__c=UserInfo.getUserId();
        request.RSM_Manager__c=UserInfo.getUserId();
        request.RSM_VP_Sales__c=UserInfo.getUserId();
        request.SE__c=UserInfo.getUserId();
        request.SE_Manager__c=UserInfo.getUserId();
        request.SE_Director__c=UserInfo.getUserId();
        insert request;
        request.Requested_End_Date__c= Date.today().adddays(30);
        update request;
        request.VirtualProduct1__c = 'EC-BASE-1Y';
        request.VirtualQuantity1__c = 10;
      
        ApexPages.StandardController stdController = new ApexPages.StandardController(request);
        CustomPOCRequestController controller = new CustomPOCRequestController(stdController);
        controller.savePage();
        
        
        Approval.ProcessSubmitRequest req1 =new Approval.ProcessSubmitRequest();
        req1.setComments('Automatic submit.');
        req1.setObjectId(request.id);
        // Submit the approval request for the account
        Approval.ProcessResult result = Approval.process(req1);
        List<Id> newWorkItemIds = result.getNewWorkitemIds();
         Approval.ProcessWorkitemRequest req2 = 
            new Approval.ProcessWorkitemRequest();
        req2.setComments('Approving request.');
        req2.setAction('Approve');
        req2.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        // Use the ID from the newly created item to specify the item to be worked
        req2.setWorkitemId(newWorkItemIds.get(0));
        // Submit the request for approval
        Approval.ProcessResult result2 =  Approval.process(req2);
        Request__c outputReq=[Select Id,Requested_End_Date__c from Request__c where Id=:request.id];
        System.assertEquals(null, outputReq.Requested_End_Date__c);
        
    }
    
    @IsTest
    public static void ClearRequestEndDate_ShouldnotClear()
    {
        Contact contact = new Contact(FirstName = 'AcmeFirstname', LastName = 'AcmeLastname', Phone='123456789', Email = 'acme@acme.com' );
        insert contact;
        Request__c request = new Request__c(POC_Contact__c = contact.Id);
        request.POC_Type__c='EdgeConnect';
        request.Extension_Justification__c='Test';
        
        request.TR_Approved__c=true;
        request.RSM_Approved__c=true;
        request.Submission_Condition_Satisfied__c=true;
        request.Target_End_Date__c=Date.today().adddays(5);
        request.Status__c='Shipped';
        insert request;
        request.Requested_End_Date__c= Date.today().adddays(30);
        update request;
        request.PhysicalProduct1__c = 'EC-XS';
        request.PhysicalQuantity1__c = 10;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(request);
        CustomPOCRequestController controller = new CustomPOCRequestController(stdController);
        controller.savePage();
        
        Request__c outputReq=[Select Id,Requested_End_Date__c from Request__c where Id=:request.id];
        System.assertNotEquals(null, outputReq.Requested_End_Date__c);
        
    }
}